[package]
name = "lumen-linalg"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }

[dependencies]
lumen-core = { path = "../lumen-core" }
rand = { workspace = true }
thiserror = { workspace = true }
thiserrorctx = { workspace = true }
paste = { workspace = true }
