from typing import Optional
from ... import Tensor

# ============================================================================= #
#                         Common                                                #
# ============================================================================= #

def linear(input: Tensor, weight: Tensor, bias: Optional[Tensor] = None) -> Tensor: ...

def softmax(xs: Tensor, dim: int) -> Tensor: ...

def log_softmax(xs: Tensor, dim: int) -> Tensor: ...

def dropout(xs: Tensor, drop_p: float) -> Tensor: ...

# ============================================================================= #
#                         Activate                                              #
# ============================================================================= #

def silu(xs: Tensor) -> Tensor: ...

def sigmoid(xs: Tensor) -> Tensor: ...

def relu(xs: Tensor) -> Tensor: ...

def hard_sigmoid(xs: Tensor) -> Tensor: ...

def leaky_relu(xs: Tensor, eps: float = 1e-5) -> Tensor: ...

# ============================================================================= #
#                         Loss                                                  #
# ============================================================================= #

def mse_loss(input: Tensor, target: Tensor, reduction="none") -> Tensor: ...

def l1_loss(input: Tensor, target: Tensor, reduction="none") -> Tensor: ...

def nll_loss(input: Tensor, target: Tensor, reduction="none") -> Tensor: ...

def cross_entropy(input: Tensor, target: Tensor, reduction="none") -> Tensor: ...

def soft_cross_entropy(input: Tensor, target: Tensor, reduction="none") -> Tensor: ...

# ============================================================================= #
#                         Norm                                                  #
# ============================================================================= #

def layer_norm(input: Tensor, weight: Optional[Tensor] = None, bias: Optional[Tensor] = None, eps: float = 1e-5) -> Tensor: ...

def rms_norm(input: Tensor, weight: Tensor, eps: float = 1e-5) -> Tensor: ...