[package]
name = "lumen-ml"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
description = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }

[dependencies]
lumen-core = { path = "../lumen-core" }
lumen-linalg = { path = "../lumen-linalg" }
rand = { workspace = true }
rand_distr = { workspace = true }
thiserror = { workspace = true }
thiserrorctx = { workspace = true }
derive_builder = { workspace = true }